### ISSUE TITLE
Better documentation - the list

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#263]
This issue is to list all features that needs better documentation. Every time you think: "This is not documented good enough", add a comment here
- [x] How to switch leveldb with other backends
- [x] [Query sorting](https://github.com/fergiemcdowall/search-index/issues/416)
- [x] New normalise option
- [x] New nGramLength format
- [x] Data format
- [x] Synonyms
- [x] Query pipeline demo
- [x] Indexing pipeline demo
- [ ] Document possibility of geographical filters
- [ ] Geohashing demo
- [x] Replication between search-index instances (i.e. server / desktop): [Case](https://github.com/fergiemcdowall/search-index/issues/278#issuecomment-215074502)
- [ ] Teaser and teaser formatting (configurable) https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/teaser-test.js
- [x] Sorting on fields <- kind of important. How to do sorting, other than `TF-IDF`: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/sorting-test.js#L127-L142
- [x] Filter on several categories: https://github.com/fergiemcdowall/search-index/issues/281
- [x] How to get filters on categories/buckets working
- [x] Field weighting (query side): Boosting
- [x] nGramLength as array

**Comment by fergiemcdowall** [comment]
-[] Synonyms

**Comment by fergiemcdowall** [comment]
- [ ] Query - Indexing pipeline demo
- [ ] Field weighting
- [ ] Document possibility of geographical filters

**Comment by eklem** [comment]
Ok, so one of my tasks is to test field weighting, query side.

**Comment by eklem** [comment]
- [ ] Replication between search-index instances (i.e. server / desktop): [Case](https://github.com/fergiemcdowall/search-index/issues/278#issuecomment-215074502)

**Comment by eklem** [comment]
- [ ] Teaser and teaser formatting (configurable) https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/teaser-test.js

**Comment by eklem** [comment]
Added how to filter: https://github.com/fergiemcdowall/search-index/pull/284

**Comment by eklem** [comment]
How to do sorting, other than `TF-IDF`: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/sorting-test.js#L127-L142

**Comment by eklem** [comment]
Filter on several categories: https://github.com/fergiemcdowall/search-index/issues/281

**Comment by eklem** [comment]
Document nGramLength correctly (array), everywhere: https://github.com/fergiemcdowall/search-index/issues/295

**Comment by eklem** [comment]
Added these to the list:

- New nGramLength format
- New normalise option
- Data format

**Comment by eklem** [comment]
query sorting

**Comment by fergiemcdowall** [comment]
It seems like the only thing left in this issue is a geohashing howto, and that has its own issue. Closing for now :)

**Comment by fergiemcdowall** [comment]
Oh- and teasers are no longer a part of the core lib
